### ISSUE TITLE
Tom's Simple Storage Inventory Cable

### ISSUE THREAD

**Issue by slamathon** [Heaser/pipe-connector#20]
Not sure if the problem lies with Pipe Connector or Tom's inventory cables, but for some reason cables connect to everything when placed with pipe connector. This doesn't happen when placing them manually.

![2024-01-05_14 49 30 (Medium)](https://github.com/Heaser/pipe-connector/assets/5495122/e0fba03e-74a9-4d3a-9cbd-520afa096991)

**Comment by Heaser** [comment]
Resolved in release 0.2.3
