### ISSUE TITLE
[1.19.2] Crash on server

### ISSUE THREAD

**Issue by aking4125** [Heaser/pipe-connector#3]
Hello, Upon adding this mod to the server, the server crashes. Clients with this mod cannot connect to the server with it installed even if they don't have it: 

[crash-2023-05-09_00.06.21-fml.txt](https://github.com/Heaser/pipe-connector/files/11427166/crash-2023-05-09_00.06.21-fml.txt)

**Comment by Heaser** [comment]
Resolved
